# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cffee4dfa16411971065205246e3f99947547426cbabce81260461f3553b6083cd7697c95b3a2b70f9a6923506bf911fa02a3f2c1737a054e9090c722b45d32

test:
  secret_key_base: bfee8a690e27d7fee5689b75cd8b2b2747f79a005167f4b76c9c4993e1bee18eadbfa38631d32c8db61872eba0be6e3d6dde785adab90a35c0025157b8a625d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
